language: php

php:
  - 5.4
  - 5.5
  - 5.6

script:
  - composer install
  - phpunit test/EventTest.php
  - phpunit test/JobStatusTest.php
  - phpunit test/JobTest.php
  - phpunit test/StatTest.php
  - phpunit test/WorkerTest.php
